
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  text/html;

    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            proxy_pass http://172.17.0.3:8080;
        }

    }

}